

version: "3.9"

services:

  mlflow:

    image: datascientest/mlflow-exam-apple:latest

    container_name: mlflow-server

    ports:
      - "5000:5000"


  api:

    build: .

    container_name: iris-api

    ports:
      - "8000:8000"

    depends_on:
      - mlflow

    env_file:
      - .env